

title: Jekyll SZ Flex
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

author: StartZeroGnu

markdown: kramdown
kramdown:
  input: GFM

gems:
  - jekyll-feed

exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README

collections:
  posts:
    permalink: /blog/posts/:title

navigation:
  Home: /
  About: /about/
